In [14]:
import numpy as np

In [18]:
valor=np.matrix([[12.500,11.800,15.900,25.300]])
valor

matrix([[12.5, 11.8, 15.9, 25.3]])

In [ ]:
#el incremento del mes de abril es de 5%#

In [19]:
marzo=np.matrix([[12,8,14,6]])
marzo

matrix([[12,  8, 14,  6]])

In [20]:
porcentaje=0.05*marzo
porcentaje

matrix([[0.6, 0.4, 0.7, 0.3]])

In [21]:
abril=marzo+porcentaje
abril

matrix([[12.6,  8.4, 14.7,  6.3]])